### ISSUE TITLE
doesn't work with Typescript

### ISSUE THREAD

**Issue by AntonPilyak** [rollup/rollup-plugin-image#10]
Works fine with plain JavaScript, but doesn't work with Typescript. Here is the repository for reproducing: https://github.com/AntonPilyak/rollup-image-bug

**Comment by ovidiu12** [comment]
As a workaround you can use https://github.com/rollup/rollup-plugin-image/issues/2#issuecomment-417919060.

**Comment by shellscape** [comment]
We're moving this plugin to https://github.com/rollup/plugins where it'll get some TLC. Keep an eye out for this repo being archived and `@rollup/plugin-images`.
