### ISSUE TITLE
doesn't work with react

### ISSUE THREAD

**Issue by Symboler** [rollup/rollup-plugin-image#12]
Error: 'default' is not exported by './logo.png'

**Comment by arvinsim** [comment]
I tried importing a `png` image and I got this error

`Error: Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)`

**Comment by whathejoe** [comment]
Fixed this by using another library: https://www.npmjs.com/package/rollup-plugin-image-files

Hope this helps.

**Comment by shellscape** [comment]
We're moving this plugin to https://github.com/rollup/plugins where it'll get some TLC. Keep an eye out for this repo being archived and `@rollup/plugin-images`.
