### ISSUE TITLE
'import' and 'export' may only appear at the top level

### ISSUE THREAD

**Issue by lsqswl** [rollup/rollup-plugin-image#8]
'import' and 'export' may only appear at the top level (26422:1141)
You may need an appropriate loader to handle this file type.

**Comment by lsqswl** [comment]
var img = new Image(); img.src = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAABmJLR0QAAAAAAAD5Q7t/AAAACXBIWXMAAAsSAAALEgHS3X78AAACjElEQVRYw73XT6gVZRjH8c9MWSKlJIligVDwFOHCihB1kSCRfyriSigUd6W0EDdZELUIQhANonAhrXIRkRJYUt7+u0hzEYI75SEoEixctEhKUKQW571wvJxz7sy553h2887v/X2/M8w8zKky8wQew0RE/OQW/DLzKXyCkzUex1JMZebaWwDfjONYjJU1JnAFC8ctkZkTOIb5uITn64g4jU3jlsjM7TiCO/A7noyICzWMWyIzJ/ERbsevBf4L1NOhcUlk5k58iNuQBf7b9Pm6OzxqiczchQ8K5zzWR8TF7kw9c9OoJDLzVRxEhXMF/sfMXN1r81wlMvNNvFPgZ7EhIi73ytb9SoaVyMy92FsOzxT4X/3yVYPCdZjC3fgbm/pNzMw8gNfK4Y/YEhFXBvXPKtBEIjMrvI/dZel7PBcR/87W3UhgkESBH8LLJTqFrRFxtUlvY4E+EluwE5Ml8hm2RcS1pp2tBHpIXMe8cuooXoqI6236WgsUifX4Vme0wtc6D9yNtl112w2ZeSf2dMFhDVYPczGtBDJzAT7HM2XpmJvnxLqxCWTmXfgCT5eld7HVzcPqRFuJpnNgEb7EdPm+iHij6/zMt2NzmaRzF8jMe3QesifK0lsR8XaP3FASAwUy8158g0fL0usRsX9AvrVENaBsKb7DSvyHVyLivQZ3rJVE1adkuc48f7jAd0XEodngw0hUPTavKPAHcQM7IuJwU3hbiWrGpgfwA1YU+GREfNwW3kai6go/VK78PlzDixHx6bDwphJVCT1S4MsK/IWIOD5XeBOJKjNX6bxqS3BV5z/iV6OCzyZRZeZF3I9/8GxEnBw1fJBEjZ/xJzaOE07PD90jQ30PjOhOHMWp/wE/W0d9sNjfqwAAAABJRU5ErkJggg=='; export default img;

**Comment by lsqswl** [comment]
How to resolve it?

**Comment by shellscape** [comment]
We're moving this plugin to https://github.com/rollup/plugins where it'll get some TLC. Keep an eye out for this repo being archived and `@rollup/plugin-images`.
